"use client";

export const statesMap = {
    "01": "JAMMU AND KASHMIR",
    "02": "HIMACHAL PRADESH",
    "03": "PUNJAB",
    "04": "CHANDIGARH",
    "05": "UTTARAKHAND",
    "06": "HARYANA",
    "07": "DELHI",
    "08": "RAJASTHAN",
    "09": "UTTAR PRADESH",
    "10": "BIHAR",
    "11": "SIKKIM",
    "12": "ARUNACHAL PRADESH",
    "13": "NAGALAND",
    "14": "MANIPUR",
    "15": "MIZORAM",
    "16": "TRIPURA",
    "17": "MEGHALAYA",
    "18": "ASSAM",
    "19": "WEST BENGAL",
    "20": "JHARKHAND",
    "21": "ODISHA",
    "22": "CHATTISGARH",
    "23": "MADHYA PRADESH",
    "24": "GUJARAT",
    "26": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "27": "MAHARASHTRA",
    "29": "KARNATAKA",
    "30": "GOA",
    "31": "LAKSHADWEEP",
    "32": "KERALA",
    "33": "TAMIL NADU",
    "34": "PUDUCHERRY",
    "35": "ANDAMAN AND NICOBAR ISLANDS",
    "36": "TELANGANA",
    "37": "ANDHRA PRADESH",
    "38": "LADAKH",
  };
  
  export const units = [
    "NONE",
    "BAGS (BAG)",
    "BOTTLES (BTL)",
    "BOX (BOX)",
    "BUNDLES (BDL)",
    "CANS (CAN)",
    "CARTONS (CTN)",
    "DOZENS (DZN)",
    "GRAMMES (GM)",
    "KILOGRAMS (KG)",
    "LITRE (LTR)",
    "METERS (MTR)",
    "MILILITRE (ML)",
    "NUMBERS (NOS)",
    "PACKS (PAC)",
    "PAIRS (PRS)",
    "PIECES (PCS)",
    "QUINTAL (QTL)",
    "ROLLS (ROL)",
    "SQUARE FEET (SQF)",
    "SQUARE METERS (SQM)",
    "TABLETS (TBS)",
  ];
  
  export const taxRates = [
    "NONE",
    "IGST@0%",
    "IGST@0.25%",
    "IGST@3%",
    "IGST@5%",
    "IGST@12%",
    "IGST@18%",
    "GST@18%",
    "IGST@28%",
    "EXEMPT",
  ];